version: "3.9"

services:
  raid-helper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-raid-helper
    env_file:
      - .env
    ports:
      - "127.0.0.1:3333:3333"
    volumes:
      - ./.data:/app/data
    restart: always
